chore: linting action improvements (#120)
* fails the lint/test action if either tests or linting fail

* wip: force a test failure

* wip: force a lint failure

* fixes tests and linting

* ignore linting for complex method

diff --git a/.github/workflows/lint-tests.yml b/.github/workflows/lint-tests.yml
--- a/.github/workflows/lint-tests.yml
+++ b/.github/workflows/lint-tests.yml
@@ -40,12 +40,22 @@ jobs:
           pip install .[dev]
           pip install .[test]
       - name: Lint with Ruff
+        id: lint
         run: |
           ruff check --output-format=github netbox_diode_plugin/
         continue-on-error: true
       - name: Test
+        id: test
         run: |
           make docker-compose-netbox-plugin-test-cover
+        continue-on-error: true
+      - name: Check results
+        if: always()
+        run: |
+          if [[ "${{ steps.lint.outcome }}" == "failure" || "${{ steps.test.outcome }}" == "failure" ]]; then
+            echo "Either linting or tests failed"
+            exit 1
+          fi
       - name: Coverage comment
         uses: orgoro/coverage@3f13a558c5af7376496aa4848bf0224aead366ac # v3.2
         if: github.event.pull_request.head.repo.full_name == github.repository
